name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Exécuter les tests unitaires
      - name: Run unit tests
        run: python -m unittest discover -s . -p "test_api.py"

      # Étape 5 : Déployer l'application (à personnaliser selon votre méthode)
      - name: Deploy application
        run: |
          echo "Déploiement"
